export enum Configuration {
  PORT = 'PORT',
  KAFKA_BROKER = 'KAFKA_BROKER',
  KAFKA_NAME_SERVICE = 'KAFKA_NAME_SERVICE',
  KAFKA_NAME_CONSUMER = 'KAFKA_NAME_CONSUMER',
  MEMORY_TOPIC = 'MEMORY_TOPIC',
  LOAD_CONSUMPTION_CRONJOB = 'LOAD_CONSUMPTION_CRONJOB',
}
