export enum Configuration {
  PORT = 'PORT',
  KAFKA_BROKER = 'KAFKA_BROKER',
  KAFKA_NAME_SERVICE = 'KAFKA_NAME_SERVICE',
  KAFKA_NAME_CONSUMER = 'KAFKA_NAME_CONSUMER',
  USER_TOPIC = 'USER_TOPIC',
}
